"""
NeoBank analytics: Streamlit interface.

Interface only. Every number on every page comes from a service module; this
file loads (cached), calls, and displays. If you find a formula here, it is in
the wrong file.

Run:  streamlit run app.py
"""

import pandas as pd
import streamlit as st

from neobank import analytics, fraud, fx, lending, loaders, reconcile, risk
from neobank.ledger import Ledger, money, to_cents

st.set_page_config(page_title="NeoBank analytics", page_icon="\U0001F3E6", layout="wide")


# ---------------------------------------------------------------------------
# Cached loaders, Streamlit re-runs this whole file on every interaction
# ---------------------------------------------------------------------------
@st.cache_data(ttl=3600)
def transactions():
    return loaders.load_transactions()


@st.cache_data(ttl=3600)
def prices():
    return loaders.load_prices()


@st.cache_data(ttl=3600)
def cards():
    return fraud.apply_rules(fraud.engineer(loaders.load_card_transactions()))


@st.cache_data(ttl=3600)
def rates():
    return loaders.load_fx_snapshot()


@st.cache_resource
def demo_ledger():
    """A worked example so the ledger page has something to show."""
    led = Ledger()
    for account in ("society", "member_mai", "supplier_print"):
        led.open_account(account)
    led.deposit("member_mai", to_cents("120.00"), memo="top-up from bank")
    led.deposit("society", to_cents("500.00"), memo="opening float")
    led.transfer("member_mai", "society", to_cents("45.00"), fee=to_cents("0.50"),
                 memo="gala ticket", key="ticket-mai-001")
    led.transfer("member_mai", "society", to_cents("45.00"), fee=to_cents("0.50"),
                 memo="gala ticket", key="ticket-mai-001")          # retry: no second charge
    led.transfer("society", "supplier_print", to_cents("180.00"), memo="posters")
    refund = led.transfer("society", "member_mai", to_cents("20.00"), memo="partial refund")
    led.reverse(refund, memo="refund issued in error")
    led.split_payment("society", ["member_mai", "supplier_print"], to_cents("10.01"),
                      memo="split the leftover float")
    return led


# ---------------------------------------------------------------------------
st.sidebar.title("NeoBank analytics")
section = st.sidebar.radio(
    "Section", ["Overview", "Spending", "Ledger", "Lending", "Portfolio risk", "Fraud queue"])
st.sidebar.divider()
st.sidebar.caption("All data is synthetic and generated by `data/generate.py`. "
                   "Educational project, not financial advice.")

try:
    tx = transactions()
except loaders.DataError as err:
    st.error(f"{err}")
    st.stop()


# ---------------------------------------------------------------------------
if section == "Overview":
    st.title("Overview")
    numbers = analytics.headline_numbers(tx)
    led = demo_ledger()

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Six-month income", f"${numbers['income']:,.0f}")
    c2.metric("Spending", f"${numbers['spend']:,.0f}")
    c3.metric("Savings rate", f"{numbers['savings_rate']:.1%}")
    c4.metric("Ledger entries", len(led.entries))

    st.subheader("Reconciliation")
    try:
        external = loaders.load_external_balances()
    except loaders.DataError as err:
        st.warning(f"No statement to reconcile against: {err}")
    else:
        rows = reconcile.reconcile(led, external)
        if reconcile.is_clean(rows):
            st.success("All accounts reconciled: internal balances match the statement exactly.")
        else:
            st.error(f"{len(reconcile.breaks(rows))} break(s) need investigating.")
        table = pd.DataFrame(rows)
        for column in ("internal", "external", "difference"):
            table[column] = table[column].map(lambda v: money(int(v)) if pd.notna(v) else ": ")
        st.dataframe(table, use_container_width=True, hide_index=True)
        st.caption("A break is a bug, a timing difference, or fraud. You cannot tell which "
                   "until you look, so nothing is auto-adjusted here.")

elif section == "Spending":
    st.title("Spending")
    numbers = analytics.headline_numbers(tx)
    c1, c2, c3 = st.columns(3)
    c1.metric("Net cash flow", f"${numbers['net_cash_flow']:,.2f}")
    c2.metric("Moved to savings", f"${numbers['transferred_to_savings']:,.0f}")
    c3.metric("Savings rate", f"{numbers['savings_rate']:.1%}")

    left, right = st.columns([3, 2])
    with left:
        st.subheader("By category")
        st.bar_chart(analytics.by_category(tx, exclude_savings=True), horizontal=True)
        st.caption("Transfers to your own savings are excluded: the money is still yours.")
    with right:
        st.subheader("Month by month")
        st.dataframe(analytics.by_month(tx), use_container_width=True)

    st.subheader("Recurring charges")
    recurring = analytics.find_recurring(tx)
    subs = recurring[recurring["cancellable"]]
    st.write(f"**{len(subs)} cancellable subscriptions** costing "
             f"${subs['abs_amount'].sum():,.2f} a month "
             f"(${subs['yearly_cost'].sum():,.2f} a year), and "
             f"{len(recurring) - len(subs)} fixed commitments.")
    st.dataframe(recurring, use_container_width=True, hide_index=True)

elif section == "Ledger":
    st.title("Ledger")
    led = demo_ledger()
    st.caption("Double-entry, append-only, idempotent. The retried ticket payment below "
               "posted exactly once.")

    accounts = sorted(led.accounts)
    account = st.selectbox("Account", accounts, index=accounts.index("member_mai"))
    rows = led.statement(account)
    table = pd.DataFrame(rows)
    if not table.empty:
        table["amount"] = table["amount"].map(money)
        table["balance"] = table["balance"].map(money)
    st.dataframe(table[["txn_id", "at", "memo", "amount", "balance"]],
                 use_container_width=True, hide_index=True)

    c1, c2 = st.columns(2)
    c1.metric("Balance", money(led.balance(account)))
    try:
        led.check_invariant()
        c2.success("Invariant holds: every transaction sums to zero.")
    except Exception as err:                      # pragma: no cover - should never happen
        c2.error(f"LEDGER OUT OF BALANCE: {err}")

elif section == "Lending":
    st.title("Lending")
    c1, c2, c3, c4 = st.columns(4)
    principal = c1.number_input("Amount", 1_000.0, 5_000_000.0, 250_000.0, 1_000.0, format="%.0f")
    rate = c2.slider("Rate (%)", 0.0, 25.0, 5.5, 0.1) / 100
    years = c3.slider("Term (years)", 1, 40, 30)
    extra = c4.number_input("Extra per month", 0.0, 50_000.0, 200.0, 50.0, format="%.0f")

    try:
        base = lending.schedule(principal, rate, years)
        fast = lending.schedule(principal, rate, years, extra=extra) if extra else base
    except ValueError as err:
        st.error(str(err))
        st.stop()

    summary = lending.summarise(base)
    m1, m2, m3 = st.columns(3)
    m1.metric("Monthly payment", f"${base['payment'].iloc[0]:,.2f}")
    m2.metric("Total interest", f"${summary['total_interest']:,.0f}")
    m3.metric("Crossover month", summary["crossover_month"])

    chart = pd.DataFrame({"standard": base["balance"]})
    if extra:
        chart["with extra"] = fast["balance"].reindex(range(len(base))).fillna(0)
    st.line_chart(chart)

    if extra:
        saving = lending.overpayment_saving(principal, rate, years, extra)
        st.success(f"An extra ${extra:,.0f} a month removes ${saving['interest_saved']:,.0f} "
                   f"of interest and {saving['months_saved']} months.")
    st.dataframe(lending.compare_terms(principal, rate), use_container_width=True, hide_index=True)

elif section == "Portfolio risk":
    st.title("Portfolio risk")
    price_data = prices()
    returns = risk.compute_returns(price_data)

    st.subheader("Per asset")
    table = risk.asset_table(price_data)
    st.dataframe(table.style.format({"total": "{:.1%}", "ann_mean": "{:.1%}", "cagr": "{:.1%}",
                                     "vol": "{:.1%}", "sharpe": "{:.2f}", "max_dd": "{:.1%}",
                                     "drag": "{:.1%}"}), use_container_width=True)
    st.caption(f"Sharpe ratios assume a {risk.RISK_FREE:.1%} risk-free rate. "
               "The drag column is the gap between the arithmetic mean and what actually compounded.")

    st.subheader("Weights")
    cols = st.columns(len(price_data.columns))
    weights = {}
    for col, asset in zip(cols, price_data.columns):
        weights[asset] = col.slider(asset, 0.0, 1.0, 0.25, 0.05)
    total = sum(weights.values())

    if abs(total - 1.0) > 1e-9:
        st.warning(f"Weights sum to {total:.2f}. Adjust them to 1.00 to see the portfolio.")
    else:
        stats = risk.portfolio_stats(returns, weights)
        check = risk.diversification_check(returns, weights)
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Return", f"{stats['ann_return']:.1%}")
        c2.metric("Volatility", f"{stats['vol']:.1%}")
        c3.metric("Sharpe", f"{stats['sharpe']:.2f}")
        c4.metric("Max drawdown", f"{stats['max_dd']:.1%}")
        st.info(f"VaR95 {stats['var95']:.2%} a day, and on the days that breach it the average "
                f"loss is {stats['shortfall95']:.2%}. Mixing these assets removed "
                f"{check['benefit']:.1%} of volatility versus holding them separately.")
        st.line_chart((1 + returns).cumprod())

elif section == "Fraud queue":
    st.title("Fraud queue")
    scored = cards()
    base = fraud.baseline(scored)

    c1, c2, c3 = st.columns(3)
    c1.metric("Transactions", f"{base['rows']:,}")
    c2.metric("Fraud base rate", f"{base['base_rate']:.2%}")
    c3.metric("Flagging nothing scores", f"{base['do_nothing_accuracy']:.2%}")
    st.caption("That last number is why accuracy is the wrong metric here.")

    review_cost = st.slider("Cost of reviewing one flagged transaction ($)", 1.0, 40.0, 4.0, 1.0)
    costs, cheapest, cheapest_total = fraud.cost_curve(scored, review_cost=review_cost)
    sweep = fraud.threshold_sweep(scored)

    threshold = st.slider("Score threshold", 3, 12, cheapest)
    row = sweep.set_index("threshold").loc[threshold]
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Flagged", int(row["flagged"]))
    c2.metric("Caught", f"{int(row['tp'])} of {base['fraud_cases']}")
    c3.metric("Precision", f"{row['precision']:.1%}")
    c4.metric("Recall", f"{row['recall']:.1%}")
    st.info(f"At a ${review_cost:,.0f} review cost the cheapest threshold is **{cheapest}** "
            f"(${cheapest_total:,.0f} total). F1 would pick "
            f"{int(sweep.loc[sweep['f1'].idxmax(), 'threshold'])}: it treats both errors as "
            f"equally costly, and your business does not.")
    st.line_chart(costs.set_index("threshold")[["missed_fraud", "review_spend", "total"]])

    st.subheader("Cases for review")
    queue = (scored[scored["score"] >= threshold]
             .sort_values(["score", "amount"], ascending=False)
             .head(25)[["txn_id", "timestamp", "amount", "country", "category", "score", "reasons"]])
    st.dataframe(queue, use_container_width=True, hide_index=True)
    st.caption("Every row carries the reasons that flagged it. A score routes a case to a human; "
               "it does not decide it.")
