/* =========================================================================
   ANALYST TRACK, LEVEL 1: the spreadsheet that does not lie
   ========================================================================= */
FQ.registerLevel({
  id: 101,
  track: 'fpa',
  position: 1,
  codename: 'variance',
  title: 'The spreadsheet that does not lie',
  tagline: 'Revenue beat the plan by 4.4% and profit missed it by 30%. Build the pack that says why, in one page, from the ledger.',
  difficulty: 3,
  minutes: 180,
  tags: ['variance analysis', 'excel', 'month end', 'fp&a'],
  summary: 'The first job of a finance analyst is the monthly close pack: what we planned, what happened, and why ' +
           'they differ. This level builds that pack for a real month of a real looking company, in a spreadsheet ' +
           'structured so that somebody else can check it, and ends with the three sentences that actually get read.',

  objectives: [
    'Read a general ledger export, including the sign convention that trips everybody up',
    'Build a budget versus actual pack that ties to the ledger, with a check cell that must be zero',
    'Split a revenue variance into the part that is volume and the part that is price',
    'Tell a favourable variance from a good one, which are not the same thing',
    'Lay out a model so that inputs, calculations and outputs are separate and nothing is hardcoded',
    'Write variance commentary that says what, why, and what happens next'
  ],

  knowledge: [
    { h: 'The job, in one paragraph' },
    { p: 'On the third working day of the month the accountants close the books, and a file lands on your desk. Your ' +
         'job is to turn it into one page that answers a single question: **we said this month would look like X, it ' +
         'looked like Y, why?** That page goes to the head of finance, and from there into a meeting where people ' +
         'decide whether to keep spending. Everything else an analyst does, the models and the dashboards and the ' +
         'board slides, is built on top of that one page.' },
    { p: 'The company in this track is **Meridian Pay**, a payments business of about $35 million a year. It is ' +
         'synthetic, generated by `data/generate_fpa_datasets.py`, and it is internally consistent: the balance sheet ' +
         'balances in all 24 simulated months, to the cent, or the file refuses to write itself. You will be closing ' +
         '**September 2025**.' },
    { money: 'The number this level ends on: revenue came in **4.4% above plan** and EBITDA came in **30% below it**. ' +
             'An analyst who reports the first number and not the second gets asked one question in the meeting and ' +
             'has no answer. The whole skill is being the person who already knew.' },

    { h: 'The file you are handed' },
    { p: 'A general ledger export. One row per account per cost centre per month, and it looks like this (these are ' +
         'the real first rows of `fpa-actuals.csv`):' },
    { table: {
      head: ['journal_id', 'month', 'cost_centre', 'account_code', 'account_name', 'amount'],
      rows: [
        ['JE000001', '2024-01', 'CC900', '4000', 'Transaction fees', '**-1,188,222.14**'],
        ['JE000002', '2024-01', 'CC900', '4100', 'Subscription fees', '**-486,000.00**'],
        ['JE000004', '2024-01', 'CC900', '5000', 'Scheme and interchange costs', '676,057.43'],
        ['JE000006', '2024-01', 'CC100', '6000', 'Salaries and wages', '448,400.00']
      ]
    }},
    { warn: 'Revenue is **negative**, because it is a credit. Every ' +
            'accounting system in the world writes revenue as a credit and credits are negative in an export. Sum the ' +
            'amount column as it comes and a profitable month reads as a catastrophe.' },
    { p: 'So the first thing you write, before any analysis, is the rule that fixes signs, and you write it **once**, ' +
         'at the boundary where the data arrives. Not in fourteen formulas further down. The rule here: revenue lines ' +
         'are flipped to positive, cost lines are left positive, and after that every number in your pack means "how ' +
         'much of this was there", which is what a reader assumes anyway.' },
    { p: 'The five files, all synthetic, all in `data/`:' },
    { table: {
      head: ['File', 'Rows', 'What it is'],
      rows: [
        ['`fpa-actuals.csv`', '318', 'The ledger, January 2024 to September 2025'],
        ['`fpa-budget.csv`', '192', 'The FY2025 plan, in whole dollars, positive'],
        ['`fpa-plan-drivers.csv`', '12', 'What the plan assumed underneath the dollars: volume, take rate, heads'],
        ['`fpa-headcount.csv`', '105', 'Heads and payroll by department by month'],
        ['`fpa-history.csv`', '21', 'The three statements, monthly, already tied']
      ]
    }},

    { h: 'Favourable is not the same as good' },
    { p: 'A variance is actual minus budget, and its sign means opposite things on opposite sides of the profit and ' +
         'loss. Revenue above plan is favourable. Cost above plan is unfavourable. Because half your lines are one and ' +
         'half are the other, a pack that shows raw differences forces every reader to work out the sign for ' +
         'themselves, and one of them will get it wrong out loud in a meeting.' },
    { p: 'So the convention, used by every finance team: **a variance column is signed so that positive is always ' +
         'favourable to profit.** For revenue that is actual minus budget. For costs it is budget minus actual. One ' +
         'formula per line type, decided once, written down at the top of the tab.' },
    { table: {
      head: ['Line', 'Actual', 'Budget', 'Variance', 'Reads as'],
      rows: [
        ['Revenue', '3,361,050', '3,220,357', '**+140,693**', 'favourable'],
        ['Cost of sales', '1,457,482', '1,290,386', '**-167,096**', 'unfavourable'],
        ['Gross profit', '1,903,569', '1,929,971', '**-26,402**', 'unfavourable'],
        ['Operating expenses', '1,637,580', '1,551,580', '**-86,000**', 'unfavourable'],
        ['EBITDA', '265,989', '378,391', '**-112,402**', 'unfavourable']
      ]
    }},
    { p: 'Read that table again, because it contains the entire lesson of the level. **Revenue beat the plan and gross ' +
         'profit missed it.** Selling more of something you make less on is a real thing that happens to real ' +
         'companies every month, and the pack has to make it visible rather than hide it inside a net number.' },

    { h: 'Price and volume, the only split you need this month' },
    { p: 'Transaction fees missed nothing: they beat the plan by $151,993. Underneath that single number are two ' +
         'movements pulling against each other, and they have different owners and different fixes.' },
    { code: 'planned:  354,224,934 of volume  x  0.6200%  =  2,196,195\nactual:   404,860,085 of volume  x  0.5800%  =  2,348,188\n                                                   -----------\n                                          variance   =   +151,993\n\nvolume effect   (404,860,085 - 354,224,934) x 0.6200%  =  +313,938\nrate effect     (0.5800% - 0.6200%) x 404,860,085      =  -161,945\n                                                          --------\n                                                          +151,993', lang: 'text' },
    { p: 'Volume was **14.3% ahead** of plan and the take rate was **6.5% behind** it. The sales team is ahead of its ' +
         'number, and pricing is losing more than half of that gain. Those are two conversations with two different ' +
         'people, and neither of them happens if the pack says "transaction fees, favourable 152k".' },
    { p: 'One more thing about that block, and it is the kind of detail that decides whether a reader trusts the rest of your pack. The two effects rounded to the nearest dollar are +313,938 and -161,944, which sum to +151,994, and the ledger says the variance was +151,993. **You are a dollar out, and you say so**: the ledger rounds every posting to the cent and your bridge multiplies two rounded rates together. Write "rounding" next to it. Plugging the dollar is how a model starts lying.' },
    { tip: 'The two effects do not add up on their own: there is a cross term, the bit where the extra volume also ' +
           'came at the lower rate. The convention above puts that cross term inside the rate effect by valuing the ' +
           'rate difference at actual volume. Any consistent convention works. Silently using a different one each ' +
           'month does not.' },
    { check: {
      q: 'Volume beat the plan by 14.3% and the take rate missed by 6.5%. What single business change would produce ' +
         'exactly that shape, and why does it matter more than the net number?',
      a: 'A mix shift towards larger merchants. Big merchants bring a lot of volume and negotiate lower pricing, so ' +
         'both numbers move at once and in opposite directions. It matters because the two have different futures: ' +
         'volume growth compounds and a lower average rate is permanent until pricing changes. A pack reporting only ' +
         'the favourable 152k tells the reader that pricing is fine, which is the opposite of what the data says. ' +
         'It also predicts the gross margin problem one line down: scheme costs scale with volume at a fixed rate, ' +
         'so if the fee rate falls while the cost rate does not, margin is squeezed from both ends.'
    }},

    { h: 'The three variances worth writing about' },
    { p: 'September has eleven lines that moved. Three of them are worth a sentence each, and the discipline is ' +
         'deciding which three rather than describing all eleven.' },
    { table: {
      head: ['What moved', 'Size', 'What it actually is'],
      rows: [
        ['Marketing programmes', '**+210,000** over', 'A campaign planned for October and November that ran in September instead. Timing, not overspend: the full year is 80,000 **under** plan'],
        ['Support salaries', '**28,000** under', 'Five heads the plan paid for that were never hired. Favourable in the pack, and a service problem in three months'],
        ['Cost centre CC600', '**96,000** under', 'A new product team that was budgeted and never created. It has never had a single actual and it never will']
      ]
    }},
    { warn: 'CC600 is the trap in this dataset. A cost centre with a budget and no actuals shows up as a large ' +
            'favourable variance every single month, and reporting it as a saving is a lie by omission: nothing was ' +
            'saved, something simply never happened. Real packs carry this for a year before somebody notices.' },
    { p: 'The rule that comes out of those three: **a variance is not an explanation.** "Marketing is 210k over" is ' +
         'the question. "Marketing is 210k over because the Q4 campaign moved into September, so the full year is 80k ' +
         'under plan and nothing needs doing" is the answer. Your pack is judged on the second one.' },

    { h: 'Laying out a model somebody else can check' },
    { p: 'Every spreadsheet that survives its first month has the same three part shape, and it is worth being dogmatic ' +
         'about it because the alternative is a file only you can open.' },
    { table: {
      head: ['Layer', 'Contains', 'Rule'],
      rows: [
        ['**Inputs**', 'Raw exports, pasted or linked, untouched', 'Never type over data. If you have to fix something, fix it in a formula in the next layer'],
        ['**Calculations**', 'The mapping, the lookups, the aggregation', 'Every cell is a formula. Colour code any cell that is a hardcoded number, and then have almost none'],
        ['**Outputs**', 'The pack, the chart, the commentary', 'Reads from calculations only. A reader should be able to follow one cell back to a raw row']
      ]
    }},
    { p: 'And one non negotiable: **a check row that must be zero**. Your pack total minus the ledger total, on the ' +
         'face of the output, in a cell that turns red when it is not zero. Not in a hidden tab, not "I checked it ' +
         'once". The number of finance careers dented by a pack that quietly stopped tying to the ledger is not small.' },
    { code: 'B48:  =SUMIFS(actuals!$F:$F, actuals!$B:$B, $B$2)     <- every ledger row for the month\nB49:  =B12+B20+B31                                      <- the pack, summed\nB50:  =ROUND(B49-B48, 2)                                <- must be 0.00\n\nConditional format on B50:  not equal to 0  ->  red fill', lang: 'text' },

    { h: 'The traps, all of which will happen to you' },
    { table: {
      head: ['Trap', 'What you see', 'The fix'],
      rows: [
        ['`SUMIF` where you needed `SUMIFS`', 'A number that is right for one month and wrong once a second month arrives', 'Use `SUMIFS` from the start, even with one condition'],
        ['`VLOOKUP` with a hardcoded column number', 'Wrong column after somebody inserts a column', '`INDEX`/`MATCH`, or `XLOOKUP`, which name the column instead of counting it'],
        ['Joining on the account **name**', 'Rows silently drop', 'Join on `account_code`. In this dataset account 5100 is called Cloud hosting in the ledger and Hosting in the plan'],
        ['A trailing space in a label', 'Two rows for the same account, one with no match', '`TRIM` everything on the way in. There is one planted in the ledger, in May'],
        ['Numbers stored as text', 'The row is skipped by `SUM` and nothing looks broken', 'Check with `ISNUMBER`. Two rows are written as text: March marketing as `180,000.00` and an April credit as `(700,200.00)`'],
        ['A duplicated export row', 'One cost centre is suddenly double', 'Count rows and count distinct journal ids. June has one duplicate, worth 590,000'],
        ['Hidden rows inside a `SUM`', 'A total nobody can reproduce', '`SUBTOTAL(109, ...)` ignores hidden rows, or better, do not hide rows in a working file']
      ]
    }},
    { p: 'Those are not hypotheticals. Every one of them is planted in `fpa-actuals.csv` or `fpa-budget.csv`, because ' +
         'the point of a teaching dataset is to be exactly as dirty as a real export and no dirtier.' },

    { h: 'The commentary, which is the part that gets read' },
    { p: 'Three sentences per material variance. What moved, why it moved, what happens next. In that order, and no ' +
         'adjectives.' },
    { code: 'Weak:\n  "Marketing spend was significantly higher than budget due to increased\n   campaign activity in the period."\n\nStrong:\n  "Marketing is 210k over plan in September because the Q4 brand campaign\n   was moved forward to catch the peak trading season. October and November\n   are now 290k under plan, so the full year is 80k favourable. No action."\n\nWeak:\n  "Support costs were favourable versus budget."\n\nStrong:\n  "Support salaries are 28k under plan because five of the six budgeted\n   hires have not been made. Volume per support head is up 40% since January.\n   Recruitment is the constraint, not the budget."', lang: 'text' },
    { p: 'The second version of each is shorter than it looks, contains a number in every sentence, and ends by telling ' +
         'the reader whether they have to do anything. That is the whole format.' },
    { check: {
      q: 'Your pack shows operating expenses 86,000 unfavourable. Marketing is 210,000 over and salaries are 124,000 ' +
         'under. How should the commentary open, and what must it not say?',
      a: 'It should open with the two gross movements rather than the net one, because they have unrelated causes and ' +
         'opposite futures: a timing difference in marketing that reverses in Q4, and a hiring shortfall in salaries ' +
         'that does not. It must not say "opex broadly in line, 86k unfavourable", which is true, useless, and hides ' +
         'both stories. It must also not report the 96,000 from CC600 as a saving, because that team was never ' +
         'created: the honest line is that the budget contains a team that does not exist and the plan should be ' +
         'reforecast.'
    }}
  ],

  tutorial: {
    intro: 'Google Sheets or Excel, whichever you have. Two imports, one mapping table, one pack, one check cell. ' +
           'Allow about ninety minutes, and resist the urge to tidy the numbers by typing over them.',
    steps: [
      {
        t: 'Import both files without touching them',
        blocks: [
          { p: 'Two tabs, named `actuals` and `budget`. In Sheets: **File, Import, Upload**, then choose *Insert new ' +
               'sheet*. In Excel: **Data, From Text/CSV**. Either way, do not retype anything, and do not sort the ' +
               'raw tabs.' },
          { code: 'actuals:  journal_id | month | cost_centre | cost_centre_name |\n          account_code | account_name | line_type | amount | memo\n\nbudget:   month | cost_centre | cost_centre_name |\n          account_code | account_name | budget_amount', lang: 'text' },
          { warn: 'Import `account_code` as **text**, not as a number. Codes like 4000 survive either way, but the ' +
                  'habit matters the first time a code starts with a zero and the leading zero disappears.' }
        ],
        check: 'actuals has 319 rows including the header, budget has 193.'
      },
      {
        t: 'Prove the file is dirty before you trust it',
        blocks: [
          { p: 'Four formulas, in four spare cells, before any analysis. They take two minutes and they are the ' +
               'difference between finding the duplicate now and finding it in the meeting.' },
          { code: '=COUNTA(actuals!A2:A)                          rows           -> 318\n=COUNTA(UNIQUE(actuals!A2:A))                  unique ids     -> 317\n=SUMPRODUCT(--NOT(ISNUMBER(actuals!H2:H318))) text amounts   -> 2\n=SUMPRODUCT(--(TRIM(actuals!F2:F318)<>actuals!F2:F318))      -> 1', lang: 'text' },
          { p: 'One duplicate journal id, two amounts stored as text, one label with a trailing space. Find the ' +
               'duplicate with a `COUNTIF` column and look at it: it is 590,000 of engineering payroll in June, ' +
               'exported twice. Decide **now** whether your pack excludes duplicates, and write the rule down.' }
        ],
        check: 'You can name the duplicated journal id, the text amount, and the account with the trailing space.'
      },
      {
        t: 'Normalise the sign once, at the boundary',
        blocks: [
          { p: 'Add one column to the calculations tab. Revenue flipped positive, everything else as it comes, text ' +
               'amounts coerced to numbers.' },
          { code: '=IF(actuals!G2="revenue", -1, 1)\n   * IFERROR(actuals!H2, VALUE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(\n       actuals!H2, "(", "-"), ")", ""), ",", "")))', lang: 'text' },
          { tip: 'That nested `SUBSTITUTE` is ugly and it belongs in exactly one column. The alternative, fixing the ' +
                 'one bad cell by hand, works until the export is refreshed and the fix is gone.' }
        ],
        check: 'The normalised column sums to a positive revenue figure and September revenue is 3,361,050.'
      },
      {
        t: 'Build the mapping table',
        blocks: [
          { p: 'A small tab that says which account codes roll into which pack line. Eleven codes, five lines. This is ' +
               'the only place the structure of your pack is written down, and it is why adding an account next month ' +
               'is a one row change.' },
          { code: 'code | pack_line          | type\n4000 | Transaction fees   | revenue\n4100 | Subscription fees  | revenue\n4200 | FX markup          | revenue\n5000 | Scheme costs       | cogs\n5100 | Cloud hosting      | cogs\n6000 | Salaries           | opex\n6100 | Marketing          | opex\n6200 | Facilities         | opex\n7000 | Depreciation       | below\n8000 | Interest           | below\n9000 | Tax                | below', lang: 'text' },
          { warn: 'Map on the **code**. The plan calls 5100 "Hosting" and the ledger calls it "Cloud hosting". Joining ' +
                  'on the name loses that line from one side and it does not warn you.' }
        ],
        check: 'Every account code in both files appears exactly once in the mapping tab.'
      },
      {
        t: 'The pack, with SUMIFS',
        blocks: [
          { code: 'actual:   =SUMIFS(calc!$D:$D, calc!$B:$B, $B$2, calc!$E:$E, $A5)\nbudget:   =SUMIFS(budget!$F:$F, budget!$A:$A, $B$2, budget!$D:$D, $A5)\nvariance: =IF($C5="revenue", actual-budget, budget-actual)\npercent:  =IFERROR(variance/budget, "")', lang: 'text' },
          { p: 'Month in `B2`, once, as a cell reference. Change it to `2025-08` and the whole pack moves to August. ' +
               'If changing the month means editing more than one cell, the pack is not finished.' }
        ],
        check: 'Revenue 3,361,050 against 3,220,357, EBITDA 265,989 against 378,391.'
      },
      {
        t: 'The check cell',
        blocks: [
          { p: 'Your pack total against the ledger total for the same month, subtracted, rounded to two decimals, ' +
               'formatted red when it is not zero.' },
          { code: '=ROUND(SUM(pack_lines) - SUMIFS(calc!$D:$D, calc!$B:$B, $B$2), 2)', lang: 'text' },
          { p: 'It will not be zero the first time. The usual causes, in order of likelihood: the duplicate is in one ' +
               'total and not the other, an account code is missing from the mapping tab, or a `SUMIFS` range is ' +
               'shorter than the data. All three are found in under a minute because the cell is red.' }
        ],
        check: 'The check cell reads 0.00 and turns red if you delete a mapping row.'
      },
      {
        t: 'The price and volume bridge',
        blocks: [
          { p: 'Two more rows, using `fpa-plan-drivers.csv` for the planned volume and take rate, and ' +
               '`fpa-history.csv` for the actual volume.' },
          { code: 'volume effect = (actual_volume - plan_volume) * plan_rate\nrate effect   = (actual_rate - plan_rate) * actual_volume\ncheck         = volume effect + rate effect - transaction fee variance  -> 0', lang: 'text' },
          { p: 'That check cell is the same idea as the last one: the decomposition has to add back up to the thing it ' +
               'decomposes, or it is a story rather than an analysis.' }
        ],
        check: '+313,938 and -161,945, summing to the +151,993 in your pack.'
      },
      {
        t: 'Write the three sentences',
        blocks: [
          { p: 'Pick the three largest variances by absolute dollars, ignore everything under 25,000, and write what ' +
               'moved, why, and what happens next. Then delete every adjective and read it again.' },
          { tip: 'Write the commentary in the workbook, next to the numbers, not in a separate document. Commentary ' +
                 'that lives somewhere else gets pasted into the next month by accident, and a stale explanation is ' +
                 'worse than none.' }
        ],
        check: 'Three variances, each with a number, a cause and a consequence, in under 120 words total.'
      }
    ]
  },

  glossary: [
    { t: 'General ledger', d: 'The accounting system of record. Every transaction the company has booked, by account, by period.' },
    { t: 'Cost centre', d: 'The team a cost belongs to. CC100 is engineering here. The answer to "whose line is this".' },
    { t: 'Chart of accounts', d: 'The numbered list of accounts. 4000s revenue, 5000s cost of sales, 6000s operating costs, by convention.' },
    { t: 'Credit', d: 'A negative amount in an export. Revenue, liabilities and equity are credits, which is why revenue exports negative.' },
    { t: 'Variance', d: 'Actual minus budget, signed so that positive means favourable to profit.' },
    { t: 'Favourable', d: 'Better for profit than planned. Not the same as good: an underspend caused by a hire that never happened is favourable and bad.' },
    { t: 'Budget', d: 'The plan, fixed at the start of the year. Not updated when reality moves, which is what makes it a benchmark.' },
    { t: 'Forecast', d: 'What you now think will happen. Updated monthly. A budget you keep changing is not a budget.' },
    { t: 'EBITDA', d: 'Earnings before interest, tax, depreciation and amortisation. The profit line an operating team can influence.' },
    { t: 'Gross margin', d: 'Gross profit over revenue. In payments it is what is left after the schemes and the acquirer take theirs.' },
    { t: 'Take rate', d: 'Revenue as a share of payment volume. 0.58% here, meaning 58 cents of every hundred dollars processed.' },
    { t: 'Price and volume variance', d: 'Splitting a revenue difference into how much was sold and what it was sold for.' },
    { t: 'Timing difference', d: 'Spend that moved between periods rather than changing in total. Reverses by definition.' },
    { t: 'Materiality', d: 'The size at which a difference is worth explaining. Chosen deliberately and written down, not felt.' },
    { t: 'Tie out', d: 'To prove that two independently produced numbers agree. A pack that does not tie to the ledger is not a pack.' },
    { t: 'SUMIFS', d: 'Sum with several conditions. The workhorse of every finance model.' },
    { t: 'INDEX/MATCH', d: 'A lookup that names the column it returns instead of counting to it, so inserting a column cannot break it.' },
    { t: 'Hardcode', d: 'Typing a number where a formula belongs. The most common cause of a model that is right once and wrong forever after.' }
  ],

  quiz: [
    { q: "The ledger export shows transaction fees as -2,348,188. What does the minus sign mean?",
      options: [
        "It is a credit, which is how every accounting export writes revenue",
        "The export is corrupt and should be requested again",
        "The company lost money on transaction fees that month",
        "The amount is a refund of previously recognised revenue"
      ],
      answer: 0,
      why: "Revenue is a credit and credits export as negatives. Normalise the sign once, where the data arrives, and every number downstream means what a reader assumes." },

    { q: "Revenue is 4.4% above plan and gross profit is 1.4% below it. Which explanation fits?",
      options: [
        "Gross profit and revenue cannot move in opposite directions",
        "Somebody has double counted revenue",
        "More was sold at a lower margin: volume up, take rate down, and costs that scale with volume",
        "The budget was wrong, so no explanation is needed"
      ],
      answer: 2,
      why: "Volume was 14.3% ahead at a take rate 6.5% behind. Scheme costs scale with volume at a fixed rate, so the margin is squeezed from both ends. This is the single most common shape in a payments business." },

    { q: "Transaction fees beat plan by 151,993. The volume effect is +313,938. What is the rate effect?",
      options: [
        "-465,882",
        "It cannot be calculated from this",
        "-161,945",
        "+161,945"
      ],
      answer: 2,
      why: "The two effects must add to the total variance, so 151,993 - 313,938 = -161,945. If your decomposition does not add back up, it is a story rather than an analysis." },

    { q: "Cost centre CC600 has a budget of 96,000 a month and has never had a single actual. How should the pack treat it?",
      options: [
        "Exclude it silently, since there is nothing to compare",
        "Show it, and say in the commentary that the team was never created and the plan needs reforecasting",
        "As a favourable variance, because the money was not spent",
        "Reallocate its budget across the other cost centres"
      ],
      answer: 1,
      why: "Nothing was saved, something never happened. Reporting it as a saving flatters the pack every month, and reallocating it hides the planning error. Show it and name it." },

    { q: "Why join the ledger to the budget on account_code rather than account_name?",
      options: [
        "Excel cannot match on text",
        "Account names are not unique within a month",
        "Codes sort faster than names",
        "Names differ between systems: 5100 is Cloud hosting in the ledger and Hosting in the plan, so a name join drops the row"
      ],
      answer: 3,
      why: "A join on a label fails silently. The row simply does not appear, the pack still totals something, and the difference shows up as an unexplained variance." },

    { q: "Marketing is 210,000 over plan in September, and October and November are now 290,000 under. What is this?",
      options: [
        "An overspend that needs approval",
        "A timing difference: the campaign moved forward, and the full year is 80,000 favourable",
        "A budgeting error in the original plan",
        "A reclassification between cost centres"
      ],
      answer: 1,
      why: "Spend that moves between periods rather than changing in total is a timing difference, and the commentary has to say so or somebody will try to cut a budget that is already under." },

    { q: "Support salaries are 28,000 under plan because five budgeted hires were never made. How is this reported?",
      options: [
        "As a favourable variance, with the service consequence named",
        "As an unfavourable variance, because hiring failed",
        "As a favourable variance and nothing more",
        "It is not a variance at all"
      ],
      answer: 0,
      why: "Favourable is an arithmetic fact and it is not the same as good. The cost line improved because capacity did not arrive, and the person reading the pack needs both halves." },

    { q: "What is the check cell for?",
      options: [
        "To count the rows in the import",
        "To check the budget was approved",
        "To confirm the formulas have no circular references",
        "To prove the pack ties to the ledger, on the face of the output, every time it is refreshed"
      ],
      answer: 3,
      why: "One cell, pack total minus ledger total, red when it is not zero. It catches a broken range or a missing mapping row in the second it happens rather than in the meeting." },

    { q: "A `SUM` over the amount column returns a number that is exactly 590,000 too high. What do you look for first?",
      options: [
        "A missing minus sign",
        "A duplicated export row",
        "A floating point rounding error",
        "A hidden row"
      ],
      answer: 1,
      why: "A round, exact, single-line discrepancy is almost always a duplicate. Count rows against count distinct on the journal id. This dataset has one, in June." },

    { q: "One amount in the file reads `(700,200.00)` and another reads `180,000.00`. What happens if you ignore them?",
      options: [
        "The import fails",
        "Nothing, spreadsheets read brackets as negative",
        "The column becomes text in most tools, the SUM skips it, and the pack is understated with no error shown",
        "It is rounded to zero"
      ],
      answer: 2,
      why: "Brackets and thousands separators make the cell text. The dangerous part is that nothing breaks: the sum simply excludes them, and the check cell is what catches it. The brackets are also a minus sign, so reading it as 653,400 gets the sign wrong as well as the type." },

    { q: "Why use INDEX/MATCH or XLOOKUP rather than VLOOKUP with a column number?",
      options: [
        "VLOOKUP cannot look up text",
        "They are faster on large files",
        "They handle duplicates automatically",
        "They name the column they return, so inserting a column in the source cannot silently change the answer"
      ],
      answer: 3,
      why: "VLOOKUP counts columns. Somebody inserts one, every lookup shifts by one, and the numbers are still plausible. That is the worst kind of wrong." },

    { q: "Where should the sign-flipping rule live?",
      options: [
        "In one column on the calculations tab, applied once where the data arrives",
        "In each formula that touches revenue",
        "In the raw import, by typing over the negatives",
        "In the commentary, as a note to the reader"
      ],
      answer: 0,
      why: "Once, at the boundary. Typing over raw data loses it on the next refresh, and scattering the rule through formulas guarantees one of them is missed." },

    { q: "What is the difference between a budget and a forecast?",
      options: [
        "The budget is fixed at the start of the year as the benchmark; the forecast is what you now expect and is updated monthly",
        "The forecast is approved by the board and the budget is not",
        "The budget covers costs and the forecast covers revenue",
        "None, the words are interchangeable"
      ],
      answer: 0,
      why: "A budget you keep editing stops being a benchmark and you can no longer tell whether you are behind. Both exist because they answer different questions." },

    { q: "Which commentary is doing its job?",
      options: [
        "\"Opex 86k unfavourable, see attached.\"",
        "\"Opex overspend driven by elevated marketing investment to capture market opportunity.\"",
        "\"Opex is 86k unfavourable: marketing 210k over on a campaign pulled into September that leaves the year 80k under, and salaries 124k under, of which 96k is a cost centre that was never created.\"",
        "\"Opex was materially above budget due to phasing and other factors.\""
      ],
      answer: 2,
      why: "The gross movements, their causes, and what the reader should do. The net number alone hides two unrelated stories, and the adjectives in the other options carry no information." },

    { q: "Your pack ties to the ledger, but the ledger itself includes a duplicated journal. What is the right answer?",
      options: [
        "Adjust the budget to match",
        "Exclude it, flag it to the accountant, and say in the commentary that the ledger is overstated by 590k until it is corrected",
        "Remove the duplicate from your calculations tab and say nothing",
        "Leave it: the pack ties, which is what matters"
      ],
      answer: 1,
      why: "Tying to a wrong number is not accuracy. The analyst who finds the error, tells the person who can fix it, and states the effect is the one who gets trusted with the next thing." }
  ],

  project: {
    title: 'The September close pack',
    story: 'It is the third working day of October. The ledger for September has landed, the plan has not moved since ' +
           'January, and the head of finance wants one page before the Thursday meeting: what we said, what happened, ' +
           'and why. Build it in a spreadsheet somebody else could pick up and refresh next month without asking you ' +
           'a single question.',
    scope: 'A spreadsheet, plus a short memo. Uses only this level: imports, SUMIFS, a lookup, a check cell, one ' +
           'chart, and words. No macros, no Python, no add-ins.',
    dataset: '{{RAW}}/data/fpa-actuals.csv',
    requirements: [
      'Both CSVs imported to their own tabs and never edited by hand',
      'A data quality tab naming the duplicate journal, the two text amounts, and the trailing-space label, with what you did about each',
      'One calculations tab where the sign is normalised exactly once',
      'A mapping table from account code to pack line, with every code in both files mapped',
      'A pack showing revenue, cost of sales, gross profit, gross margin, operating expenses by cost centre, and EBITDA',
      'Actual, budget, variance and variance percent columns, with variance signed so positive is always favourable',
      'The month driven by one cell, so changing it moves the whole pack',
      'A check cell that is zero and turns red when it is not, on the face of the pack',
      'A price and volume bridge for transaction fees that sums back to the reported variance',
      'One chart: the five largest variances, sorted, with the favourable and unfavourable ones visually distinct',
      'Commentary on the three largest variances, each with what moved, why, and what happens next, under 120 words total',
      'A one page memo (markdown or PDF) with the five headline numbers and your three sentences',
      'The workbook and the memo in your portfolio repository, with a README saying how to refresh it for October'
    ],
    starter: {
      lang: 'text',
      code: '# FinQuest analyst level 1: the September close pack\n#\n# Tab layout, in this order, left to right:\n#\n#   actuals     raw import, never edited\n#   budget      raw import, never edited\n#   quality     four formulas: rows, unique ids, non-numeric amounts, untrimmed labels\n#               (expect 318, 317, 2, 1)\n#   map         account_code -> pack_line -> type (revenue / cogs / opex / below)\n#   calc        one row per ledger row: normalised amount, pack line, month\n#   pack        the output. Month in B2. Check cell at the bottom.\n#   bridge      volume effect, rate effect, and the check that they add up\n#   memo        five numbers and three sentences\n#\n# The rule for the whole file: if a number in the pack cannot be traced back\n# to a row in actuals or budget by clicking through formulas, it does not\n# belong in the pack.\n#\n# Before you start, write your materiality threshold in one cell and use it:\n#\n#   materiality = 25,000        <- explain everything above this, nothing below\n'
    },
    tests: [
      'The check cell reads zero, and deleting one row from the mapping tab turns it red',
      'Changing the month cell from 2025-09 to 2025-08 moves the entire pack, with no other edit',
      'September revenue is 3,361,050 and EBITDA is 265,989',
      'The price and volume bridge sums to the transaction fee variance of +151,993',
      'Every variance in the pack is signed so that a positive number is favourable to profit',
      'The data quality tab names the duplicated journal id and says whether the pack includes it',
      'No cell in the pack contains a typed number except the month, the materiality threshold, and labels',
      'The commentary names a cause and a consequence for each of the three largest variances',
      'A reader who has never seen the file can follow any pack number back to a ledger row in three clicks'
    ],
    rubric: [
      { pts: 25, t: 'It ties', d: 'The pack agrees with the ledger, the check cell proves it on the face of the output, and the duplicate is handled deliberately.' },
      { pts: 20, t: 'It is structured', d: 'Inputs, calculations and outputs are separate, the month is one cell, and nothing is hardcoded.' },
      { pts: 20, t: 'It explains', d: 'The price and volume split adds up, and the three commentary lines have a cause and a consequence each.' },
      { pts: 20, t: 'It is honest', d: 'CC600 is shown rather than banked, the hiring shortfall is named as a risk, and the timing difference is called a timing difference.' },
      { pts: 15, t: 'It is refreshable', d: 'Somebody else can produce October from this file, using the README, without asking you anything.' }
    ],
    stretch: [
      'Add a rolling twelve month chart of revenue and gross margin from the ledger, without breaking the check cell',
      'Add a second check: the pack against fpa-history.csv, which was produced independently of your mapping',
      'Rebuild the pack for August and explain why the gross margin was 61.8% that month and 56.6% in September',
      'Write the one paragraph you would send if you found the duplicate at 6pm on the day the pack is due'
    ],
    solutionPath: 'solutions/fpa-01'
  },

  faq: [
    { q: 'Excel or Google Sheets?',
      a: 'Either. Every formula in this level exists in both. Sheets is easier to share and version, Excel is what you will find in most finance teams, and the structure matters more than the tool. If you have the choice, learn the keyboard shortcuts of whichever one is on the desk you are sitting at.' },
    { q: 'Is a spreadsheet not a step backwards from the code in the other track?',
      a: 'No. A spreadsheet is the interface finance runs on, and being the person whose workbook can be audited is worth more in the first two years than being the person who wrote a script nobody else can open. Level 3 of this track automates exactly this pack, and it is a better automation for having been built by hand once.' },
    { q: 'How long should the pack take?',
      a: 'The first one, a day. By the third month, ninety minutes, and most of that is the commentary. If it still takes a day in month three, the model is doing something by hand that it should be doing by formula.' },
    { q: 'What if my number does not match the one in the level?',
      a: 'Check the duplicate first: 590,000 in June, which does not touch September. Then check that both text amounts are being read, in March and April. Then check that your SUMIFS ranges cover all 318 rows rather than stopping at the last row you could see when you wrote them.' },
    { q: 'Do I really need a memo as well as the pack?',
      a: 'The memo is the part that gets read. Most people above you will never open the workbook: they will read five numbers and three sentences and make a decision. The workbook exists so that the memo can be trusted.' }
  ]
});
